### ISSUE TITLE
All files

### ISSUE THREAD

**Issue by VietTran0302** [MicrosoftLearning/AZ500-AzureSecurityTechnologies.fr-fr#1]
All files in image folder are untranslated yet

**Comment by olprod** [comment]
Hello contributor,

Thank you for your contribution! We are processing your suggestions and we will update you shortly.   

Kind regards,  

Microsoft Worldwide Learning Team

**Comment by Chenpeng21** [comment]
This is an image issue, so I can't fix it.

**Comment by stonezy123** [comment]
This image file all in the WEB, so we can't fix it. Rejected.
