### ISSUE TITLE
index

### ISSUE THREAD

**Issue by HienThuThiDai** [MicrosoftLearning/AZ500-AzureSecurityTechnologies.fr-fr#11]
English: 
Labs

Current Translation:
Laboratoires

Suggested Translation:
Labos

Description:
As a general rule, please translate "laboratory" as 'laboratoire" and "lab' as "labo" (and never use "lab" in French. Please make a global search and fix all the occurrences in this batch

**Comment by olprod** [comment]
Hello contributor,

Thank you for your contribution! We are processing your suggestions and we will update you shortly.   

Kind regards,  

Microsoft Worldwide Learning Team

**Comment by Chenpeng21** [comment]
Run the bugfix tool and waiting for result. [ICMS QUERY](https://wus-000.icms.osi.office.net/vantagepoint/QueryPanel.aspx?Tenant=C%26E&Query=PFZQUT48TEZPPkZhbHNlPC9MRk8%2bPElEPkZhbHNlPC9JRD48RUxDPkZhbHNlPC9FTEM%2bPEFNUD5GYWxzZTwvQU1QPjxTT0hSSVI%2bRmFsc2U8L1NPSFJJUj48U0hSUD5GYWxzZTwvU0hSUD48U0FUTz5GYWxzZTwvU0FUTz48U0FMTz5UcnVlPC9TQUxPPjxRRT4%2bMjwvUUU%2bPFFUPj48UVIgSWQ9IjEiIENQSUQ9IjAiPkN1cnJlbnQ7RmlsZXM7SG9zdCBDb250ZW50IFN0b3JlO0VxdWFsO0xBQl9BWjUwMDwvUVI%2bPFFSIElkPSIyIiBDUElEPSIwIj5hbmQ7Q3VycmVudDtMb2NGaWxlcztMYW5ndWFnZTtFcXVhbDtGcmVuY2g8L1FSPjxRUiBJZD0iMyIgQ1BJRD0iMCI%2bYW5kO0N1cnJlbnQ7RmlsZXM7SG9zdCBGaWxlIFJlZmVyZW5jZTtDb250YWlucztpbmRleDwvUVI%2bPC9RVD48Ukc%2bPEdDPk5VTEw8L0dDPjwvUkc%2bPC9WUFE%2b)

**Comment by stonezy123** [comment]
![image](https://user-images.githubusercontent.com/49666210/185055306-3e061dd3-3b6b-4719-9ff7-71fcf1f64e2d.png)
